CreatePresentationWebsite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^home/', include('rst2html5presentation.urls')),
    url(r'^$', include('rst2html5presentation.urls')),
    url(r'^admin/', admin.site.urls),
]

rst2html5presentation/urls.py
from django.conf.urls import url

from . import views

app_name = 'rst2html5presentation'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^watchpresentation/$', views.watchPresentation, name='watchpresentation'),
    url(r'^watchpresentation/uploadimage/$', views.uploadImagePage, name='uploadimagepage'),
    url(r'^watchpresentation/uploadimage/result/$', views.uploadImageResult, name='uploadimageresult'),
    url(r'^watchpresentation/getuploadimage/(?P<author>\w+)/(?P<presentationname>\w+)/(?P<imagename>\w+)/$', views.getUploadImage, name='getuploadimage'),
]

rst2html5presentation/models.py
from django.db import models

# Create your models here.

rst2html5presentation/views.py
from django.shortcuts import render
from django.http import HttpRequest , HttpResponse , HttpResponseRedirect
from django.template import loader
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage

import os


def index(request):
	return render(request, 'rst2html5presentation/index.html', {})

def watchPresentation(request):
	# initialization
	fileName = request.GET["presentationName"]
	author = request.GET["author"]
	userDirPath = "rst2html5presentation/Userdata/{}".format(author)
	if not os.path.exists(userDirPath):
		os.makedirs(userDirPath)
	presentationDirPath = "{}/{}".format(userDirPath,fileName)
	if not os.path.exists(presentationDirPath):
		os.makedirs(presentationDirPath)
	presentationStyle = request.GET["presentationStyle"]
	# write file
	text = request.GET["rstInput"]
	rstFile = open("{}/{}.rst".format(presentationDirPath,fileName), "w")
	rstFile.write(text)
	rstFile.close()
	#create presentation
	os.system('rst2html5 {} {}/{}.rst > {}/{}.html'.format(presentationStyle,presentationDirPath,fileName,presentationDirPath,fileName))
	# open presentation
	htmlFile = open("{}/{}.html".format(presentationDirPath,fileName), "r")
	htmlText = htmlFile.read()
	return HttpResponse(htmlText)

def uploadImagePage(request):
	presentationName = request.GET["presentationName"]
	author = request.GET["author"]
	return render(request, 'rst2html5presentation/uploadimagepage.html',{"presentationName":presentationName,"author":author})

def uploadImageResult(request):
	imageFile = request.FILES['imageFile']
	imageName = imageFile.name
	presentationName = request.POST["presentationName"]
	author = request.POST["author"]
	dirPath = 'rst2html5presentation/Userdata/{}/{}/images/'.format(author,presentationName)
	if not os.path.exists(dirPath):
		os.makedirs(dirPath)
	saveFilePath = default_storage.save(dirPath, imageFile)
	os.rename(saveFilePath,"{}{}".format(dirPath,imageName))
	imageNameWithOutType = imageName.split(".jpg")[0]
	return render(request, 'rst2html5presentation/uploadimageresultpage.html',{"presentationName":presentationName,"author":author,"imagename":imageNameWithOutType})

def getUploadImage(request,author,presentationname,imagename):
	imageDir = "rst2html5presentation/Userdata/{}/{}/images".format(author,presentationname)
	print(imageDir)
	if not os.path.exists(imageDir):
		os.makedirs(imageDir)
	with open("{}/{}.jpg".format(imageDir,imagename), "rb") as image:
		return HttpResponse(image.read(), content_type="image/jpeg")

rst2html5presentation/templates/rst2html5presentation/index.html
<html>
<head>
<title>Create Presentation</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rst2html5presentation/style.css' %}" />
<script src="{% static 'rst2html5presentation/angular-1.5.5/angular.min.js' %}"></script>
<script>
var isEditorSettingOpening = false;
var editorFontSize = "12px";//document.getElementById("rstInput").style["font-size"];
var editorFontColor = "#000000";
function openEditorSettingPanel(){
	var editorSettingPanel = document.getElementById("editorSettingPanel")
	if (isEditorSettingOpening){
		editorSettingPanel.innerHTML = "";
		isEditorSettingOpening = false;
	}
	else {
		editorSettingPanel.appendChild(document.createTextNode("--------------------------------------------------"));
		editorSettingPanel.appendChild(document.createElement("br"));
		editorSettingPanel.appendChild(document.createTextNode("Font Size : "));
		var fontSizeInput = document.createElement("input");
		fontSizeInput.setAttribute("type", "text");
		fontSizeInput.setAttribute("id", "editorFontSizeInput");
		fontSizeInput.setAttribute("value", editorFontSize);
		editorSettingPanel.appendChild(fontSizeInput);
		editorSettingPanel.appendChild(document.createElement("br"));
		editorSettingPanel.appendChild(document.createTextNode("Font Color : "));
		var fontColorInput = document.createElement("input");
		fontColorInput.setAttribute("type", "text");
		fontColorInput.setAttribute("id", "editorFontColorInput");
		fontColorInput.setAttribute("value", editorFontColor);
		editorSettingPanel.appendChild(fontColorInput);
		editorSettingPanel.appendChild(document.createElement("br"));
		var applyButton = document.createElement("a");
		applyButton.setAttribute("href", "javascript:applySetting();");
		applyButton.style.fontSize = "60%"
		applyButton.innerHTML = "Apply Setting";
		editorSettingPanel.appendChild(applyButton);
		editorSettingPanel.appendChild(document.createElement("br"));
		editorSettingPanel.appendChild(document.createTextNode("--------------------------------------------------"));
		isEditorSettingOpening = true;
	}
}
function applySetting(){
	editorFontSize = document.getElementById("editorFontSizeInput").value;
	editorFontColor = document.getElementById("editorFontColorInput").value;
	alert("Font Size : "+editorFontSize+"Font Color :"+editorFontColor);
	editor = document.getElementById("rstInput");
	editor.style.fontSize = editorFontSize;
	editor.style.color = editorFontColor;
}
</script>

<script>
var app = angular.module('previewShowAndRSTinput', []);
app.controller('previewShowAndRSTinputController', function($scope) {
	$scope.displayStatus = false;
	$scope.showPreview = function() {
		$scope.displayStatus = !$scope.displayStatus;
	}
});
</script>

</head>
<body>
<div id='logo'>
<center><h1 class="logo"><b>Create Your <span style="color:#FFB347;">Presentation</span></b></center>
</div>

<div id='panel'>
<center>
<h2>With your <span style="color:#FFB347;">reStructuredText</span></h2>
<form id="rstBox">

<b><span style="color:#FFB347;">Presentation</span> Name :</b>
<input type="text" name="presentationName" placeholder="Enter your Presentation name here" maxlength="200" size="40">
<br>
<b>Author :</b>
<input type="text" name="author" placeholder="Enter your name here" maxlength="20" size="20" value="Guest">
<br>

<div ng-app="previewShowAndRSTinput" ng-controller="previewShowAndRSTinputController">
<button src="" ng-click="showPreview()" formaction="{% url 'rst2html5presentation:watchpresentation' %}" formtarget="previewShowFrame">Show Preview</button>
<button ng-show="displayStatus" formaction="{% url 'rst2html5presentation:watchpresentation' %}" formtarget="previewShowFrame">Refresh</button>
<br>
<button formaction="{% url 'rst2html5presentation:uploadimagepage' %}" formtarget="_blank">Insert Image</button>
<table style="width:100%;height:70%;">
<td ng-show="displayStatus" style="width:40%;">
<div id="previewShow">
<iframe name="previewShowFrame" width="100%" height="100%" frameborder="1"></iframe>
</div>
</td>
<td style="width:60%;">
<div id="RSTtextarea">
<textarea name="rstInput" id="rstInput" class="rstInput" placeholder="Enter your reStructuredText here">
</textarea>
</div>
</td>
</table>
</div>

<br>

<div>
<a href="javascript:openEditorSettingPanel();" style="font-size:60%;">Editor Setting</a><br>
<div id="editorSettingPanel"></div>

<span style="color:#FFB347;">Presentation</span> Style : 
<select name="presentationStyle" id='presentationStyle'>
    <option value="">Clean</option>
    <option value="--deck-js">Deck</option>
    <option value="--jquery --reveal-js">Reveal</option>
    <option value="--jquery --bootstrap-css">Bootstrap</option>
</select><br>
</div>

<br>
<div>
<input type="submit" value="Watch Presentation" id="watch" formaction="{% url 'rst2html5presentation:watchpresentation' %}" formtarget="_blank"> 
</div>
<br>
</form> 


</center><br>
</div>

</body>
</html>

rst2html5presentation/templates/rst2html5presentation/uploadimagepage.html
<html>
<head>
<title>Create Presentation</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rst2html5presentation/style.css' %}" />
<script src="{% static 'rst2html5presentation/angular-1.5.5/angular.min.js' %}"></script>
</head>
<body>

<h1>Upload Image For Insert</h1>
<form action="{% url 'rst2html5presentation:uploadimageresult' %}" method="post" enctype="multipart/form-data">
<b><span style="color:#FFB347;">Presentation</span> Name :</b>
<input type="text" readonly name="presentationName" size="40" value="{{ presentationName }}">
<br>
<b>Author :</b>
<input type="text" readonly name="author" size="20" value="{{ author }}">
<br>
{% csrf_token %}
Browse Image:
<input type="file" name="imageFile" id="imageFile"><br>
<input type="submit" value="Upload" name="submit">
</form><br>

</body>
</html>

rst2html5presentation/templates/rst2html5presentation/uploadimageresultpage.html
<html>
<head>
<title>Create Presentation</title>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rst2html5presentation/style.css' %}" />
<!-- with out angular for the a moment -->
</head>
<body>

<b><span style="color:#FFB347;">Presentation</span> Name :</b>
<input type="text" readonly name="presentationName" size="40" value="{{ presentationName }}">
<br>
<b>Author :</b>
<input type="text" readonly name="author" size="20" value="{{ author }}">
<br>

Copy and Paste to your reStructuredText
<input readonly value=".. image:: getuploadimage/{{ author }}/{{ presentationName }}/{{ imagename }}"><br><br>
<img src="{% url 'rst2html5presentation:getuploadimage' author presentationName imagename %}">

</body>
</html>